version: "3"
services:
  backend:
    build: .
    image: backend-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend-network
    restart: always
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_db
    ports:
      - "3306:3306"
    networks:
      - backend-network
    volumes:
      - mysql-volume:/var/lib/mysql
    restart: always
networks:
  backend-network:
volumes:
  mysql-volume:
