version: "3"
services:
  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    container_name: db
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - backend-network
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      # - mysql-volume:/var/lib/mysql
    restart: always
  backend:
    build: .
    image: backend-api
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - backend-network
    restart: always
networks:
  backend-network:
# volumes:
#   mysql-volume:
